### PR TITLE
Repeat the same CI test

### PR DESCRIPTION
**Pull request by serut**
I just want to see if it always happens

### CODE REVIEW

**Comment by serut** [comment]
11 fail, 11 success ... 🤕

**Comment by serut** [comment]
10 times this error :
```
> winsleague@2.0.0 coverage-app-full /home/ubuntu/winsleague/app
> node_modules/spacejam/bin/spacejam --driver-package practicalmeteor:mocha-console-runner test --full-app --coverage 'out_lcovonly out_coverage out_html in_coverage' --settings settings.coverage.json

spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> A patch (Meteor 1.4.1.2) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
spacejam: meteor mongodb is ready

Unable to resolve some modules:

  "bcrypt-pbkdf" in
/home/ubuntu/winsleague/app/node_modules/sshpk/lib/formats/ssh-private.js
(os.linux.x86_64)
  "jodid25519" in
/home/ubuntu/winsleague/app/node_modules/sshpk/lib/private-key.js
(os.linux.x86_64)
  "jsbn" in /home/ubuntu/winsleague/app/node_modules/sshpk/lib/utils.js
(os.linux.x86_64)
  "ecc-jsbn" in /home/ubuntu/winsleague/app/node_modules/sshpk/lib/dhe.js
(os.linux.x86_64)
  "ecc-jsbn/lib/ec" in
/home/ubuntu/winsleague/app/node_modules/sshpk/lib/dhe.js (os.linux.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save bcrypt-pbkdf jodid25519 jsbn ecc-jsbn
[..]
spacejam: meteor is ready
spacejam: spawning phantomjs
phantomjs: Running tests at http://localhost:4096/local using test-in-console and coverage
phantomjs: TypeError: undefined is not an object (evaluating 'Package['service-configuration'].ServiceConfiguration')
    http://localhost:4096/packages/accounts-base.js?hash=db584b046b0a64d03bfcbf1cd84a8b38f83ddc0d: 870
    http://localhost:4096/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3: 809
    http://localhost:4096/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3: 821
spacejam: phantomjs exited with code: 6
spacejam: killing meteor
spacejam: meteor killed with signal: SIGTERM
spacejam: Unhandled error in meteor client side code. Exiting.
```

1 time this error:
```
> node_modules/spacejam/bin/spacejam --driver-package practicalmeteor:mocha-console-runner test --full-app --coverage 'out_lcovonly out_coverage out_html in_coverage' --settings settings.coverage.json
[..]
I20161017-13:38:55.359(0)? info: Updating PoolTeam undefeated and defeated weeks 8QDy6DMX3G3rv62fv
W20161017-13:38:55.403(0)? (STDERR) debug: PoolTeams.update 8QDy6DMX3G3rv62fv with undefeatedWeeks: 0, defeatedWeeks: 0, numberAffected: 1
W20161017-13:38:55.404(0)? (STDERR) debug: Done finding PoolTeams who picked leagueTeamId BS7pxnFSdbaMHDxrA for seasonId K3tjTX9qydaepsHo3
W20161017-13:38:55.426(0)? (STDERR) debug: seasonLeagueTeam factory created: _id=uEbPcWFrKzH64oev7, leagueId=dSsRki8CCvHJnZrtS, seasonId=K3tjTX9qydaepsHo3, leagueTeamId=BS7pxnFSdbaMHDxrA, abbreviation=NYG, wins=10, losses=6, ties=0, homeWins=6, homeLosses=3, homeTies=0, awayWins=4, awayLosses=3, awayTies=0, pointsFor=17, pointsAgainst=14, closeWins=0, closeLosses=0, createdAt=Mon Oct 17 2016 13:38:55 GMT+0000 (UTC)
I20161017-13:38:55.427(0)? info: Done loading fixtures
I20161017-13:38:55.483(0)? info: Logging in...
I20161017-13:38:55.829(0)? info: Logged in!
I20161017-13:38:56.350(0)? info: currentPath: /pools/WvHy4g8GYDKeewCX4/teams/new
W20161017-13:38:56.717(0)? (STDERR) debug: newDoc:  poolId=WvHy4g8GYDKeewCX4, userEmail=test123@test.com, userTeamName=Dummy Dummies
W20161017-13:38:56.760(0)? (STDERR) debug: Created new user: 2CyTbB6RYiSNzRpq7
I20161017-13:38:56.765(0)? ====== BEGIN MAIL #0 ======
I20161017-13:38:56.766(0)? (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
I20161017-13:38:56.766(0)? MIME-Version: 1.0
I20161017-13:38:56.767(0)? Date: Mon, 17 Oct 2016 13:38:56 +0000
I20161017-13:38:56.767(0)? From: "Wins League" <team@winsleague.com>
I20161017-13:38:56.768(0)? To: test123@test.com
I20161017-13:38:56.769(0)? Subject: Welcome to Wins League
I20161017-13:38:56.769(0)? Content-Type: text/plain; charset=utf-8
I20161017-13:38:56.770(0)? Content-Transfer-Encoding: quoted-printable
I20161017-13:38:56.770(0)? 
I20161017-13:38:56.771(0)? Wins League is a simple form of fantasy sports, but just as much fun.
I20161017-13:38:56.772(0)? =20=20
I20161017-13:38:56.772(0)? To activate your account, simply click the link below:
I20161017-13:38:56.773(0)? =20
I20161017-13:38:56.775(0)? http://localhost:4096/enroll-account/gObHY1quPo_SHoLZiOJzak6bqLGkldEPfxmIdN7FIz-
I20161017-13:38:56.775(0)? ====== END MAIL #0 ======
W20161017-13:38:56.822(0)? (STDERR) debug: newDoc:  poolId=WvHy4g8GYDKeewCX4, userTeamName=Dummy Dummies, userId=2CyTbB6RYiSNzRpq7, leagueId=dSsRki8CCvHJnZrtS, seasonId=K3tjTX9qydaepsHo3, seasonYear=2015, teamSummary=, totalWins=0, totalLosses=0, totalGames=0, totalPlusMinus=0, undefeatedWeeks=0, defeatedWeeks=0, closeWins=0, closeLosses=0, createdAt=Mon Oct 17 2016 13:38:56 GMT+0000 (UTC)
C: Full-app test of PoolTeams Full-app test of PoolTeams.new should create new pool team : failed
```

**Comment by noahsw** [comment]
@serut I didn't dig too deep but it seems like you're making progress. What do you think? Do we have any idea what's causing the underlying error?

**Comment by serut** [comment]
I updated spacejam so the url "https://github.com/serut/spacejam/tarball/windows-suppport-rc4" is still valid. You just need to add an meteor npm install (https://github.com/winsleague/winsleague/pull/353/files#diff-29944324a3cbf9f4bd0162dfe3975d88R3) or rebuild without cache and most of errors will vanish

**Pull request closed without merging**
