### PR TITLE
Feature/218 coverage

### LINKED ISSUE #218: Get code coverage working
https://github.com/kadirahq/flow-router/issues/608#issuecomment-241204493

### PR DESCRIPTION
**Pull request by noahsw**
@serut let's use this as a clean branch

fixes #218 

Requires #175

### CODE REVIEW

**Comment by serut** [comment]
- use meteor-coverage v 1.1.3
- replace [meteor|spacejam]-mocha to the long command with --driver-package
- but you need to add spacejam and things inside packages.json
- update circle.yml file

**Comment by noahsw** [comment]
ah, I didn't realize you were going to require meteor 1.4. I probably should have kept your original PR then instead of rebasing against master's meteor 1.3...

I made your other changes though in this PR. all the files changed is from shrinkpack. apparently they changed from .tgz to .tar

**Comment by serut** [comment]
Ah sorry I didnt knew before today that meteor-coverage-app requires 1.4. It explains a lot indeed. 
Have a good re-rebasing !

**Comment by noahsw** [comment]
Still having trouble with `IS_COVERAGE_ACTIVE`. See https://circleci.com/gh/winsleague/winsleague/741. Is this fixed in your version that requires Meteor 1.4?

**Comment by serut** [comment]
When you will upgrade your app to Meteor 1.4, then meteor-coverage will be readen by node 4.7 instead of node 0.10.46. That makes a huge difference, and yes it fixes that bug

**Pull request closed without merging**
